version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./.local/certs:/etc/pki/tls/certs
      - ./.local/private:/etc/pki/tls/private
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"

  express:
    build:
      context: .
      dockerfile: /docker/express/Dockerfile
      target: prod

  database:
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_PASSWORD: "ChangeMe123"
      POSTGRES_DB: "SampleDatabase"
    ports:
      # For local dev, expose the database outside the docker network in case devs want to
      # access it on their machine (e.g. HeidiSQL, PostgreSQL Explorer, etc)
      - "5432:5432"
